repos:
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "1.8.0"
  hooks:
    - id: pyproject-fmt
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.1
  hooks:
    - id: ruff-format
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
